locals {
  vpc_data = {
    sre = {
      cidr                                 = "10.0.0.0/16"
      azs_count                            = 3
      public_subnets                       = ["10.0.0.0/22", "10.0.4.0/22", "10.0.8.0/22"]
      private_subnets                      = ["10.0.16.0/22", "10.0.20.0/22", "10.0.24.0/22"]
      enable_flow_log                      = true
      create_flow_log_cloudwatch_log_group = true
      create_flow_log_cloudwatch_iam_role  = true
      flow_log_max_aggregation_interval    = 60
      public_subnet_suffix                 = "public"
      private_subnet_suffix                = "private"
      enable_nat_gateway                   = true
      one_nat_gateway_per_az               = true
      single_nat_gateway                   = false
      enable_dns_hostnames                 = true
      enable_dns_support                   = true
      enable_s3_endpoint                   = true
      enable_dhcp_options                  = true
      shared_tag                           = "shared"
      logs_retention                       = 90
      s3_endpoint_type                     = "Gateway"
      dynamodb_endpoint_type               = "Gateway"
    },
    dev = {
      cidr                                 = "10.10.0.0/16"
      azs_count                            = 3
      public_subnets                       = ["10.10.0.0/22", "10.10.4.0/22", "10.10.8.0/22"]
      private_subnets                      = ["10.10.16.0/22", "10.10.20.0/22", "10.10.24.0/22"]
      enable_flow_log                      = true
      create_flow_log_cloudwatch_log_group = true
      create_flow_log_cloudwatch_iam_role  = true
      flow_log_max_aggregation_interval    = 60
      public_subnet_suffix                 = "public"
      private_subnet_suffix                = "private"
      enable_nat_gateway                   = true
      one_nat_gateway_per_az               = true
      single_nat_gateway                   = false
      enable_dns_hostnames                 = true
      enable_dns_support                   = true
      enable_s3_endpoint                   = true
      enable_dhcp_options                  = true
      shared_tag                           = "shared"
      logs_retention                       = 90
      s3_endpoint_type                     = "Gateway"
      dynamodb_endpoint_type               = "Gateway"
    },
    qa = {
      cidr                                 = "10.20.0.0/16"
      azs_count                            = 3
      public_subnets                       = ["10.20.0.0/22", "10.20.4.0/22", "10.20.8.0/22"]
      private_subnets                      = ["10.20.16.0/22", "10.20.20.0/22", "10.20.24.0/22"]
      enable_flow_log                      = true
      create_flow_log_cloudwatch_log_group = true
      create_flow_log_cloudwatch_iam_role  = true
      flow_log_max_aggregation_interval    = 60
      public_subnet_suffix                 = "public"
      private_subnet_suffix                = "private"
      enable_nat_gateway                   = true
      one_nat_gateway_per_az               = true
      single_nat_gateway                   = false
      enable_dns_hostnames                 = true
      enable_dns_support                   = true
      enable_s3_endpoint                   = true
      enable_dhcp_options                  = true
      shared_tag                           = "shared"
      logs_retention                       = 90
      s3_endpoint_type                     = "Gateway"
      dynamodb_endpoint_type               = "Gateway"
    },
    stg = {
      cidr                                 = "10.30.0.0/16"
      azs_count                            = 3
      public_subnets                       = ["10.30.0.0/22", "10.30.4.0/22", "10.30.8.0/22"]
      private_subnets                      = ["10.30.16.0/22", "10.30.20.0/22", "10.30.24.0/22"]
      enable_flow_log                      = true
      create_flow_log_cloudwatch_log_group = true
      create_flow_log_cloudwatch_iam_role  = true
      flow_log_max_aggregation_interval    = 60
      public_subnet_suffix                 = "public"
      private_subnet_suffix                = "private"
      enable_nat_gateway                   = true
      one_nat_gateway_per_az               = true
      single_nat_gateway                   = false
      enable_dns_hostnames                 = true
      enable_dns_support                   = true
      enable_s3_endpoint                   = true
      enable_dhcp_options                  = true
      shared_tag                           = "shared"
      logs_retention                       = 90
      s3_endpoint_type                     = "Gateway"
      dynamodb_endpoint_type               = "Gateway"
    },
    prod = {
      cidr                                 = "10.40.0.0/16"
      azs_count                            = 3
      public_subnets                       = ["10.40.0.0/22", "10.40.4.0/22", "10.40.8.0/22"]
      private_subnets                      = ["10.40.16.0/22", "10.40.20.0/22", "10.40.24.0/22"]
      enable_flow_log                      = true
      create_flow_log_cloudwatch_log_group = true
      create_flow_log_cloudwatch_iam_role  = true
      flow_log_max_aggregation_interval    = 60
      public_subnet_suffix                 = "public"
      private_subnet_suffix                = "private"
      enable_nat_gateway                   = true
      one_nat_gateway_per_az               = false
      single_nat_gateway                   = false
      enable_dns_hostnames                 = true
      enable_dns_support                   = true
      enable_s3_endpoint                   = true
      enable_dhcp_options                  = true
      shared_tag                           = "shared"
      logs_retention                       = 90
      s3_endpoint_type                     = "Gateway"
      dynamodb_endpoint_type               = "Gateway"
    },

  }
}